# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
  default: mainnet-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.4.0
  - GalloDaSballo/fair-selling@rc.2
  - OpenZeppelin/openzeppelin-contracts@4.5.0/


# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version: null
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0"
      - "@seller=GalloDaSballo/fair-selling@rc.2"
      - "@oz=OpenZeppelin/openzeppelin-contracts@4.5.0/contracts/"


